Add Openstack support
dicedtomatoreal/typex pull request #154
Opened 2022-06-21 11:35 UTC by cestef

This pretty much adds support for OS's ["Swift"](https://docs.openstack.org/swift/latest/index.html) service (Object Storage), feel free to reach me out for any modifications etc.

2022-06-21 16:48 UTC, diced requested changes
Could you add the new configuration changes to the `src/lib/config/readConfig.ts` file? And for the Openstack.ts where you import the logger use `lib/logger` instead of `../logger.

2022-06-21 19:41 UTC, cestef commented
Should be all good now ! Removed the weird library and also added openstack to the config validation part (switched from endless `if`s and `else if`s to a regular `switch/case`)

2022-06-21 19:42 UTC, cestef commented
Oh yeah and I also removed a weird ESlint rule that was forcing me to indent the switch cases weirdly, don't know if that was intentional, feel free to remove it

2022-06-22 00:52 UTC, diced approved these changes

2022-06-22 00:54 UTC, merged