fix: NaN on stat card
dicedtomatoreal/typex pull request #179
Opened 2022-10-04 01:53 UTC by ItzDerock

Small PR that prevents NaN from showing (due to dividing by 0) on stat card.
![image](https://user-images.githubusercontent.com/14848722/193717637-ae182ce8-50a8-4242-9b2a-58136d50fec2.png)

2022-10-04 21:42 UTC, axisiscool requested changes

2022-10-04 21:42 UTC, axisiscool commented on src/lib/utils/client.ts
> +  if(initial === 0) return Infinity;
```suggestion
  if (initial === 0 && final === 0) return 0;
  if (initial === 0) return Infinity;
```

2022-10-06 05:30 UTC, diced approved these changes

2022-10-06 05:43 UTC, axisiscool approved these changes

2022-10-06 05:48 UTC, diced commented
Next time please remember to sign your commits...

2022-10-15 19:22 UTC, merged