feat: add limits
dicedtomatoreal/typex pull request #201
Opened 2022-10-20 03:47 UTC by TacticalTechJay

Along with limits, uploading text page now catches and shows you any error.

2022-10-20 03:47 UTC, TacticalTechJay commented
for #164

2022-10-20 03:49 UTC, TacticalTechJay commented
This is open for debate if it should even be included with Zipline.

2022-10-21 12:36 UTC, ItzDerock commented on prisma/schema.prisma
> +  limit_by   String   @default("count")
I think using an enum for `type_time` and `limit_by` would be better than using String.

2022-10-21 14:02 UTC, axisiscool requested changes

2022-10-21 14:02 UTC, axisiscool commented on src/pages/api/auth/create.ts
> +    }
```suggestion
    for (const [x, y] of Object.entries(limits)) {
      if (ends.includes(x)) data[x] = [y][0];
    }
```
Useless jump statement. It'll continue forward regardless of whether or not the `if` check passes.

2022-10-21 14:02 UTC, axisiscool commented on src/pages/api/user/[id].ts
> +        }
```suggestion
        for (const [x, y] of Object.entries(req.body.limits)) {
          if (ends.includes(x)) data[x] = [y][0];
        }
```
Ditto

2022-10-29 22:17 UTC, TacticalTechJay commented
Limits are canceled 👏

2022-10-29 22:17 UTC, closed without merging