some startup script stuff
dicedtomatoreal/typex pull request #286
Opened 2023-02-16 00:00 UTC by IThundxr

doesnt affect normal users helps me alot :3

2023-02-17 01:00 UTC, diced requested changes
Please add the following changes.

Make sure that the `tini` package is added in line 49 so that the `ENTRYPOINT` layer will work.

2023-02-17 01:00 UTC, diced commented on Dockerfile
> +COPY entrypoint.sh /usr/local/bin/docker-entrypoint.sh
```suggestion
COPY docker-entrypoint.sh /zipline
```

Should be `docker-entrypoint.sh` instead of `entrypoint.sh`, and lets just move it into /zipline.

2023-02-17 01:00 UTC, diced commented on Dockerfile
> +RUN ln -s /usr/local/bin/docker-entrypoint.sh /
```suggestion

```

Remove redundant step due to above comment. Also the link does not work.

2023-02-17 01:00 UTC, diced commented on Dockerfile
> +ENTRYPOINT ["tini", "--", "docker-entrypoint.sh"]
```suggestion
ENTRYPOINT ["tini", "--", "/zipline/docker-entrypoint.sh"]
```

Change to /zipline/docker-entrypoint.sh to reflect changes

2023-02-17 02:37 UTC, IThundxr commented
Fixed those things you asked for

2023-02-18 03:09 UTC, diced approved these changes

2023-02-18 03:09 UTC, merged